src/main/java/org/example/advaned/kimaram/unitthree/AirConditioner.java
src/main/java/org/example/advaned/kimaram/unitthree/Light.java
src/main/java/org/example/advaned/kimaram/unitthree/MusicPlayable.java
src/main/java/org/example/advaned/kimaram/unitthree/PowerControllable.java
src/main/java/org/example/advaned/kimaram/unitthree/README.md
src/main/java/org/example/advaned/kimaram/unitthree/SmartSpeaker.java
src/main/java/org/example/advaned/kimaram/unitthree/TemperatureControllable.java
src/main/java/org/example/advaned/kimaram/unitthree/TimerControllable.java
src/main/java/org/example/advaned/kimaram/unittwo/NotificationSender.java
src/main/java/org/example/basic/kimaram/unitfour/Student.java
src/main/java/org/example/basic/kimaram/unitfour/StudentMain.java

Kimaram 0716 PR 

---

src/main/java/org/example/basic/parkminji/unitfive/Book.java

(feat) unit five complete

---

src/main/java/org/example/basic/kimaram/unitsix/LambdaExample1.java
src/main/java/org/example/basic/kimaram/unitsix/LambdaExample2.java
src/main/java/org/example/basic/kimaram/unitsix/LambdaExample3.java
src/main/java/org/example/basic/kimaram/unitsix/LambdaExample4.java
src/main/java/org/example/basic/kimaram/unitsix/LambdaExample5.java
src/main/java/org/example/basic/kimaram/unitsix/homework.sql

(feat) 0718 과제 PR 요청

---

src/main/java/org/example/basic/parkminji/unitsix/LambdaEx01.java
src/main/java/org/example/basic/parkminji/unitsix/LambdaEx02.java
src/main/java/org/example/basic/parkminji/unitsix/LambdaEx03.java
src/main/java/org/example/basic/parkminji/unitsix/LambdaEx04.java
src/main/java/org/example/basic/parkminji/unitsix/LambdaEx05.java
src/main/java/org/example/basic/parkminji/unitsix/create_tables.sql.sql

(feat) unit six and sql complete

---

src/main/java/org/example/advaned/mindongil/unitfive/EmailService.java
src/main/java/org/example/advaned/mindongil/unitfive/MessageService.java
src/main/java/org/example/advaned/mindongil/unitfive/Notification.java
src/main/java/org/example/advaned/mindongil/unitfive/SmsService.java
src/main/java/org/example/basic/mindongil/unitseven/Animal.java
src/main/java/org/example/basic/mindongil/unitseven/Cat.java
src/main/java/org/example/basic/mindongil/unitseven/Dog.java
src/main/java/org/example/basic/mindongil/unitseven/InheritanceExample.java
src/main/java/org/example/basic/mindongil/unitseven/OverrideExample.java

feat: basic unitseven, advaned unitfive

---

src/main/java/org/example/advaned/kimaram/unitsix/DoubleSingleton.java
src/main/java/org/example/advaned/kimaram/unitsix/HolderSingleton.java
src/main/java/org/example/advaned/kimaram/unitsix/LazySingleton.java
src/main/java/org/example/advaned/kimaram/unitsix/Main.java
src/main/java/org/example/advaned/kimaram/unitsix/SynchronizedSingleton.java
src/main/java/org/example/basic/kimaram/uniteight/payment/CreditCardPayment.java
src/main/java/org/example/basic/kimaram/uniteight/payment/KakaoPay.java
src/main/java/org/example/basic/kimaram/uniteight/payment/Main.java
src/main/java/org/example/basic/kimaram/uniteight/payment/Payment.java
src/main/java/org/example/basic/kimaram/uniteight/shape/Circle.java
src/main/java/org/example/basic/kimaram/uniteight/shape/Main.java
src/main/java/org/example/basic/kimaram/uniteight/shape/Rectangle.java
src/main/java/org/example/basic/kimaram/uniteight/shape/Shape.java

Kimaram 0722 과제 PR 요청

---

src/main/java/org/example/basic/mindongil/uniteight/Circle.java
src/main/java/org/example/basic/mindongil/uniteight/CreditCardPayment.java
src/main/java/org/example/basic/mindongil/uniteight/KakaoPay.java
src/main/java/org/example/basic/mindongil/uniteight/Main.java
src/main/java/org/example/basic/mindongil/uniteight/Payment.java
src/main/java/org/example/basic/mindongil/uniteight/Rectangle.java
src/main/java/org/example/basic/mindongil/uniteight/Shape.java

feat: basic uniteight

---

src/main/java/org/example/basic/parkminji/uniteight/abstractclass/Circle.java
src/main/java/org/example/basic/parkminji/uniteight/abstractclass/Main.java
src/main/java/org/example/basic/parkminji/uniteight/abstractclass/Rectangle.java
src/main/java/org/example/basic/parkminji/uniteight/abstractclass/Shape.java
src/main/java/org/example/basic/parkminji/uniteight/interfaceuse/CreditCardPayment.java
src/main/java/org/example/basic/parkminji/uniteight/interfaceuse/KakaoPay.java
src/main/java/org/example/basic/parkminji/uniteight/interfaceuse/Main.java
src/main/java/org/example/basic/parkminji/uniteight/interfaceuse/Payment.java

(feat) unit eight complete

---

src/main/java/org/example/basic/leeseungyeon/unitnine/Main.java
src/main/java/org/example/basic/leeseungyeon/unitnine/Student.java

feat. unitnine 과제업로드

---

src/main/java/org/example/basic/parkminji/unitnine/Main.java
src/main/java/org/example/basic/parkminji/unitnine/Student.java

(basic) unit nine - Student 클래스 캡슐화 및 리스트 출력
- `Student` 클래스에 캡슐화 적용 (`private` 필드, `getter/setter`)
- 점수 유효성 검사 (`0~100` 범위)
- 학년 유효성 검사 (`1~6` 범위)
- 점수에 따른 등급 반환 메서드 `getGradeLevel()` 구현
- `ArrayList<Student>`에 여러 학생 객체 추가 및 출력
- 잘못된 입력에 대한 테스트 포함 (점수/학년 범위 벗어날 경우 메시지 출력)
- `org.example.basic.parkminji.unitnine.Student`
- `org.example.basic.parkminji.unitnine.Main`
```
이름: 민지
점수: 92
등급: A
학년: 3
이름: 만지
점수: 75
등급: C
학년: 2
이름: 먼지
점수: 58
등급: F
학년: 1
이름: 몬지
점수: 85
등급: B
학년: 4
잘못된 입력 테스트:
점수 범위 오류 (0~~100)
학년 범위 오류 (1~~6)
이름: 오류학생
점수: 0
등급: F
학년: 0
```

(feat) unit nine complete

---

src/main/java/org/example/advaned/gojunho/uniteight/Notification/Email.java
src/main/java/org/example/advaned/gojunho/uniteight/Notification/EmailFactory.java
src/main/java/org/example/advaned/gojunho/uniteight/Notification/Main.java
src/main/java/org/example/advaned/gojunho/uniteight/Notification/Notification.java
src/main/java/org/example/advaned/gojunho/uniteight/Notification/NotificationFactory.java
src/main/java/org/example/advaned/gojunho/uniteight/Notification/SMS.java
src/main/java/org/example/advaned/gojunho/uniteight/Notification/SMSFactory.java
src/main/java/org/example/advaned/gojunho/uniteight/Notification/Slack.java
src/main/java/org/example/advaned/gojunho/uniteight/Notification/SlackFactory.java
src/main/java/org/example/advaned/gojunho/uniteight/Payment/CardPayment.java
src/main/java/org/example/advaned/gojunho/uniteight/Payment/CardPaymentFactory.java
src/main/java/org/example/advaned/gojunho/uniteight/Payment/KakaoPayFactory.java
src/main/java/org/example/advaned/gojunho/uniteight/Payment/Kakaopay.java
src/main/java/org/example/advaned/gojunho/uniteight/Payment/Main.java
src/main/java/org/example/advaned/gojunho/uniteight/Payment/Payment.java
src/main/java/org/example/advaned/gojunho/uniteight/Payment/PaymentFactory.java
src/main/java/org/example/basic/gojunho/unitten/Animal/Animal.java
src/main/java/org/example/basic/gojunho/unitten/Animal/AnimalPrinter.java
src/main/java/org/example/basic/gojunho/unitten/Animal/Cat.java
src/main/java/org/example/basic/gojunho/unitten/Animal/Dog.java
src/main/java/org/example/basic/gojunho/unitten/Animal/Main.java
src/main/java/org/example/basic/gojunho/unitten/Box/Box.java
src/main/java/org/example/basic/gojunho/unitten/Box/Main.java
src/main/java/org/example/basic/gojunho/unitten/Product/Book.java
src/main/java/org/example/basic/gojunho/unitten/Product/Main.java
src/main/java/org/example/basic/gojunho/unitten/Product/Phone.java
src/main/java/org/example/basic/gojunho/unitten/Product/PriceCalculator.java
src/main/java/org/example/basic/gojunho/unitten/Product/Product.java
src/main/java/org/example/basic/gojunho/unitten/Util/Main.java
src/main/java/org/example/basic/gojunho/unitten/Util/Util.java

basic unitten, advaned uniteigth complete

(feat) basic unitten, advaned uniteigth complete

---

src/main/java/org/example/basic/parkminji/unitten/genericclass/Box.java
src/main/java/org/example/basic/parkminji/unitten/genericclass/GenericClassTest.java
src/main/java/org/example/basic/parkminji/unitten/genericinterface/Book.java
src/main/java/org/example/basic/parkminji/unitten/genericinterface/InterfaceGenericTest.java
src/main/java/org/example/basic/parkminji/unitten/genericinterface/Phone.java
src/main/java/org/example/basic/parkminji/unitten/genericinterface/PriceCalculator.java
src/main/java/org/example/basic/parkminji/unitten/genericinterface/Product.java
src/main/java/org/example/basic/parkminji/unitten/genericmethod/GenericMethodTest.java
src/main/java/org/example/basic/parkminji/unitten/genericmethod/Util.java
src/main/java/org/example/basic/parkminji/unitten/wildcard/Animal.java
src/main/java/org/example/basic/parkminji/unitten/wildcard/AnimalPrinter.java
src/main/java/org/example/basic/parkminji/unitten/wildcard/Cat.java
src/main/java/org/example/basic/parkminji/unitten/wildcard/Dog.java
src/main/java/org/example/basic/parkminji/unitten/wildcard/WildcardTest.java

Java 제네릭(Generic)에 대한 실습 과제 수행 후 각 주제별로 하위 패키지를 나눠 구현.
총 4단계로 구성된 과제 main 브랜치로 병합
---
- `Box<T>` 제네릭 클래스 정의
- 문자열 및 정수 타입으로 인스턴스 생성하여 테스트 (`GenericClassTest`)
- `Util.printAll(T[] arr)` 제네릭 메서드 구현
- 문자열 배열과 정수 배열을 출력하는 테스트 코드 작성
- `Animal`, `Dog`, `Cat` 클래스 정의
- `List<? extends Animal>`을 매개변수로 받는 `AnimalPrinter` 구현
- `List<Dog>`, `List<Cat>`을 출력하는 테스트 코드 작성
- `Product` 인터페이스 정의
- `Book`, `Phone` 클래스에서 `getPrice()` 구현
- `PriceCalculator.calculateTotal(List<T>)` 메서드에서 제네릭 타입 제한 적용
- 가격 총합 계산 테스트 (`InterfaceGenericTest`)
---
---
- 패키지 경로: `org.example.basic.parkminji.unitten`
- 각 단계별 서브패키지 사용: `genericclass`, `genericmethod`, `wildcard`, `genericinterface`

feat: 제네릭 (unitten) 구현 및 테스트 코드

---

src/main/java/org/example/advaned/gojunho/unitnine/Circle.java
src/main/java/org/example/advaned/gojunho/unitnine/PrototypeDemo.java
src/main/java/org/example/advaned/gojunho/unitnine/Rectangle.java
src/main/java/org/example/advaned/gojunho/unitnine/Shape.java
src/main/java/org/example/basic/gojunho/uniteleven/IntegerCheck.java
src/main/java/org/example/basic/gojunho/uniteleven/ListExample.java
src/main/java/org/example/basic/gojunho/uniteleven/Student.java
src/main/java/org/example/basic/gojunho/uniteleven/fruit.java

basic uniteleven, advaned unitnine complete

(feat) basic uniteleven, advaned unitnine complete

---

src/main/java/org/example/basic/bangjihyun/uniteleven/InputList.java
src/main/java/org/example/basic/bangjihyun/uniteleven/NumberList.java
src/main/java/org/example/basic/bangjihyun/uniteleven/StudentList.java

🍎Java List 실습 코드 작성 및 개선
List<String>을 활용한 과일 목록 입력 프로그램 구현
사용자 입력 기능 추가 (Scanner 이용)
중복 입력 방지 기능 추가 (Set 활용)
특정 과일 검색 기능 구현
입력값 하드코딩 및 입력 반복 오류 수정
😕 어려웠던 부분
System.out.print() 사용 시 잘못된 인자 전달로 컴파일 오류 발생
for문 안에서 중복으로 add() 호출하여 과일이 과도하게 추가됨
Scanner 입력이 작동하지 않는 것처럼 보여서 실행 흐름 이해에 혼동

(feat) unit eleven complete

---

src/main/java/org/example/basic/parkminji/uniteleven/FruitCollector.java
src/main/java/org/example/basic/parkminji/uniteleven/ListExample.java
src/main/java/org/example/basic/parkminji/uniteleven/NumberAnalyzer.java
src/main/java/org/example/basic/parkminji/uniteleven/StudentListManager.java

Java의 `List` 인터페이스에 대한 과제.
총 4개의 클래스로 구성, 각 기능별로 단일 클래스로 구현.
---
- `ArrayList<String>` 활용 기본 예제
- 요소 추가, 삭제, 삽입
- `for-each` 문을 통한 전체 목록 출력
- 학생 이름 목록 추가, 삭제
- 인덱스 기반 조회 및 전체 출력
- 정수 10개를 `List`에 저장
- 최대값과 최소값 출력
- 오름차순 정렬 후 리스트 출력
- `Scanner`를 사용해 사용자로부터 과일 이름 5개 입력받아 리스트 구성
- 입력 후 전체 목록 출력
---
---
- `org.example.basic.parkminji.uniteleven.ListExample`
- `org.example.basic.parkminji.uniteleven.StudentListManager`
- `org.example.basic.parkminji.uniteleven.NumberAnalyzer`
- `org.example.basic.parkminji.uniteleven.FruitCollector`
---
```
전체 과일 목록:
Apple
Mango
Cherry
전체 학생 목록: [Alice, Bob, David, Eve]
1번 인덱스 학생: Bob
최대값: 9, 최소값: 0
정렬된 리스트: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
과일 이름 5개를 입력하세요:
1번째 과일: Apple
...
입력한 과일 목록: [Apple, ...]
```

feat: Java List 실습 (unit eleven) - 리스트 추가/삭제/조회/정렬

---

src/main/java/org/example/advaned/gojunho/unitten/AdapterMain.java
src/main/java/org/example/advaned/gojunho/unitten/Electonic110V.java
src/main/java/org/example/advaned/gojunho/unitten/Electronic220V.java
src/main/java/org/example/advaned/gojunho/unitten/SocketAdapter.java
src/main/java/org/example/basic/gojunho/unittwelve/Age.java
src/main/java/org/example/basic/gojunho/unittwelve/AgeException.java
src/main/java/org/example/basic/gojunho/unittwelve/convert.java
src/main/java/org/example/basic/gojunho/unittwelve/divide.java

basic unittwelve, advaned unitten complete

(feat) basic unittwelve, advaned unitten complete

---

src/main/java/org/example/basic/leeseungyeon/uniteight/Circle.java
src/main/java/org/example/basic/leeseungyeon/uniteight/Main.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Assignment/AgeException.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Assignment/AgeValidator.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Assignment/App.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Assignment/Divider.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Assignment/InputReader.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Assignment/NumberParser.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Example/Example1.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Example/Example2.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Example/Example3.java
src/main/java/org/example/basic/leeseungyeon/unittwelve/Example/MyException.java

🧪 실습 과제
💼 숫자 나누기 프로그램
사용자에게 정수 두 개 입력받기
0으로 나누면 ArithmeticException 처리
결과 또는 예외 메시지 출력
💼 문자열 숫자 변환
문자열을 Integer.parseInt()로 숫자 변환
잘못된 입력 시 NumberFormatException 처리
"입력 오류입니다" 메시지 출력
💼 사용자 정의 예외 만들기
나이를 매개변수로 받아서
19세 미만일 경우 AgeException 발생
사용자 정의 예외 클래스 직접 구현 (throw / throws 사용)

feat. unittwelve add  uniteight

---

src/main/java/org/example/basic/parkminji/unittwelve/AgeCheckApp.java
src/main/java/org/example/basic/parkminji/unittwelve/AgeChecker.java
src/main/java/org/example/basic/parkminji/unittwelve/AgeException.java
src/main/java/org/example/basic/parkminji/unittwelve/DivisionApp.java
src/main/java/org/example/basic/parkminji/unittwelve/StringToIntegerApp.java

Java의 `Exception`(예외 처리)에 대한 과제.  
총 3개의 실습으로 구성, 각 주제별로 클래스를 분리하여 단일 책임 원칙에 따라 구현.
---
- 사용자로부터 두 정수를 입력받아 나누기 수행
- `0`으로 나누는 경우 `ArithmeticException` 예외 처리
- 잘못된 입력 형식에 대한 `NumberFormatException`, `InputMismatchException` 처리
- 입력 로직과 연산 로직을 메서드로 분리하여 클린 코드 적용
- 문자열을 `Integer.parseInt()`로 정수 변환
- 변환 실패 시 `NumberFormatException` 예외 처리
- 예외 발생 시 입력값을 포함한 명확한 메시지 출력
- 변환 로직을 별도 메서드로 분리하여 가독성 향상
- 사용자로부터 나이를 입력받아 검증
- 19세 미만일 경우 사용자 정의 예외 `AgeException` 발생
- 나이 검증 로직은 `AgeChecker` 클래스로 분리
- 예외 객체에 입력 나이 정보를 포함하여 추후 활용 가능성 고려
- 예외 메시지를 통해 상세 정보 제공
---
---
- `org.example.basic.parkminji.unittwelve.DivisionApp`
- `org.example.basic.parkminji.unittwelve.StringToIntegerApp`
- `org.example.basic.parkminji.unittwelve.AgeCheckApp`
- `org.example.basic.parkminji.unittwelve.AgeChecker`
- …

feat: 예외 처리 실습 (unit twelve)

---

src/main/java/org/example/advaned/kimaram/unitten/AdapterMain.java
src/main/java/org/example/advaned/kimaram/unitten/Electronic110V.java
src/main/java/org/example/advaned/kimaram/unitten/Electronic220V.java
src/main/java/org/example/advaned/kimaram/unitten/SocketAdapter.java
src/main/java/org/example/basic/kimaram/unittwelve/age/AgeException.java
src/main/java/org/example/basic/kimaram/unittwelve/age/AgeMain.java
src/main/java/org/example/basic/kimaram/unittwelve/converter/StringToIntegerConverter.java
src/main/java/org/example/basic/kimaram/unittwelve/divide/NumberDivider.java
src/main/java/org/example/basic/kimaram/unittwelve/example/Example1.java
src/main/java/org/example/basic/kimaram/unittwelve/example/Example2.java
src/main/java/org/example/basic/kimaram/unittwelve/example/Example3.java
src/main/java/org/example/basic/kimaram/unittwelve/example/MyException.java

- Exception 처리
- 어댑터 패턴 구현
📁 src/main/java/org/example/basic/kimaram/unittwelve/
```
📁 age
├── AgeException.java
└── AgeMain.java
📁 converter
└── StringToIntegerConverter.java
📁 divide
└── NumberDivider.java
📁 example
├── Example1.java
├── Example2.java
└── Example3.java
```
📁 src/main/java/org/example/advaned/kimaram/unitten/
```
├── AdapterMain.java
├── Electronic110V.java
├── Electronic220V.java
└── SocketAdapter.java
```

Kimaram 0728 과제  PR 요청

---

src/main/java/org/example/advaned/yunbyeongchang/unitten/AdapterMain.java
src/main/java/org/example/advaned/yunbyeongchang/unitten/Electronic110V.java
src/main/java/org/example/advaned/yunbyeongchang/unitten/Electronic220V.java
src/main/java/org/example/advaned/yunbyeongchang/unitten/SocketAdapter.java
src/main/java/org/example/advaned/yunbyeongchang/unitten/struct.txt
src/main/java/org/example/basic/yunbyeongchang/unittwelve/example/Exception.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/example/Exceptions.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/example/customexception/CustomException.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/example/customexception/CustomExceptionProcessor.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/homework/agecheck/AgeException.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/homework/agecheck/CheckAge.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/homework/agecheck/Main.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/homework/dividenum/Divider.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/homework/dividenum/Main.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/homework/dividenum/ScannerNumber.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/homework/parseint/Main.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/homework/parseint/ParseInt.java
src/main/java/org/example/basic/yunbyeongchang/unittwelve/voca.txt

basic
+ Exception 예제 연습
+ Divider, ParseInt, CheckAge 프로그램 구현
+ Divider 구조에 try-with-resource 문 사용 연습
advanced
+ Adapter 예제 연습

feat: basic unittwelve / advaned unitten completed

---

src/main/java/org/example/basic/bangjihyun/unitthirteen/OptionalExample.java
src/main/java/org/example/basic/bangjihyun/unitthirteen/OptionalMapFilter.java
src/main/java/org/example/basic/bangjihyun/unitthirteen/OptionalNullSafe.java
src/main/java/org/example/basic/bangjihyun/unitthirteen/UserService.java

🍎 NullPointerException 실습
Optional을 활용해 NullPointerException 방지 로직 구현
사용자 이메일 조회 로직을 클린코드 원칙에 따라 단순화 및 가독성 개선
🍎 어려웠던 점
Optional로 NPE 방지 및 로직 단순화.
null/공백 입력 처리 추가.
클린코드와 예외 처리의 균형 맞추는 부분이 가장 까다로웠음.

(feat) unit thirteen complete

---

src/main/java/org/example/advaned/kimaram/uniteleven/coffee/BasicCoffee.java
src/main/java/org/example/advaned/kimaram/uniteleven/coffee/Coffee.java
src/main/java/org/example/advaned/kimaram/uniteleven/coffee/CoffeeDecorator.java
src/main/java/org/example/advaned/kimaram/uniteleven/coffee/CoffeeShop.java
src/main/java/org/example/advaned/kimaram/uniteleven/coffee/Milk.java
src/main/java/org/example/advaned/kimaram/uniteleven/coffee/Mocha.java
src/main/java/org/example/advaned/kimaram/uniteleven/pizza/Cheese.java
src/main/java/org/example/advaned/kimaram/uniteleven/pizza/Olives.java
src/main/java/org/example/advaned/kimaram/uniteleven/pizza/Pepperoni.java
src/main/java/org/example/advaned/kimaram/uniteleven/pizza/Pizza.java
src/main/java/org/example/advaned/kimaram/uniteleven/pizza/PizzaDecorator.java
src/main/java/org/example/advaned/kimaram/uniteleven/pizza/PizzaShop.java
src/main/java/org/example/advaned/kimaram/uniteleven/pizza/PlainPizza.java
src/main/java/org/example/basic/kimaram/unitthirteen/NpeExample.java
src/main/java/org/example/basic/kimaram/unitthirteen/OptionalExample.java
src/main/java/org/example/basic/kimaram/unitthirteen/OptionalMapFilter.java
src/main/java/org/example/basic/kimaram/unitthirteen/OptionalNullSafe.java
src/main/java/org/example/basic/kimaram/unitthirteen/SafeNullCheck.java
src/main/java/org/example/basic/kimaram/unitthirteen/UserService.java

Kimaram 0730 PR 요청합니다

---

src/main/java/org/example/basic/parkminji/unitthirteen/NullPointerExample.java
src/main/java/org/example/basic/parkminji/unitthirteen/OptionalBasicUsage.java
src/main/java/org/example/basic/parkminji/unitthirteen/OptionalMapFilter.java
src/main/java/org/example/basic/parkminji/unitthirteen/OptionalNullSafe.java
src/main/java/org/example/basic/parkminji/unitthirteen/SafeNullHandler.java
src/main/java/org/example/basic/parkminji/unitthirteen/UserService.java

Java의 NullPointerException 발생 원인 이해 및 null-safe 코드를 작성하는 방법을 학습하기 위한 예제 코드 추가.
- null 체크를 통한 예외 방지 방법 실습
- Optional<T> 클래스를 활용한 안전한 값 처리 및 흐름 제어 예제 포함
---
| 파일명 | 설명 |
|--------|------|
| `NullPointerExample.java` | null 값을 참조할 경우 발생하는 NPE 시나리오 구현 |
| `SafeNullHandler.java` | if 문을 통한 null 값 안전 처리 |
| `OptionalBasicUsage.java` | Optional의 기본 메서드 (`of`, `isPresent`, `orElse`) 사용 예제 |
| `OptionalNullSafe.java` | `Optional.ofNullable()`을 활용한 null-safe 처리 |
| `OptionalMapFilter.java` | `filter`와 `map`을 이용한 조건 검사 및 변환 처리 예제 |
| `UserService.java` | 메서드 반환값으로 Optional을 사용하는 예제 (`orElse` 활용) |
---

feat: NullPointerException 방지 및 Optional 활용 예제 추가

---

src/main/java/org/example/basic/parkgwanghoon/UnitEleven/ListInputExample.java
src/main/java/org/example/basic/parkgwanghoon/UnitEleven/NumberListExample.java
src/main/java/org/example/basic/parkgwanghoon/UnitEleven/StudentListExample.java
src/main/java/org/example/basic/parkgwanghoon/UnitThirteen/NpeExample.java
src/main/java/org/example/basic/parkgwanghoon/UnitThirteen/OptionalExample.java
src/main/java/org/example/basic/parkgwanghoon/UnitThirteen/OptionalMapFilter.java
src/main/java/org/example/basic/parkgwanghoon/UnitThirteen/OptionalNullSafe.java
src/main/java/org/example/basic/parkgwanghoon/UnitThirteen/SafeNullCheck.java
src/main/java/org/example/basic/parkgwanghoon/UnitThirteen/UserService.java
src/main/java/org/example/basic/parkgwanghoon/UnitTwelve/DividingExceptionExample.java
src/main/java/org/example/basic/parkgwanghoon/UnitTwelve/NumFormatExceptionExample.java
src/main/java/org/example/basic/parkgwanghoon/UnitTwelve/PGChecker.java
src/main/java/org/example/basic/parkgwanghoon/UnitTwelve/PGException.java

Parkgwanghoon

---

src/main/java/org/example/advaned/gojunho/unittwelve/BasicRemote.java
src/main/java/org/example/advaned/gojunho/unittwelve/LGTV.java
src/main/java/org/example/advaned/gojunho/unittwelve/Main.java
src/main/java/org/example/advaned/gojunho/unittwelve/RemoteControl.java
src/main/java/org/example/advaned/gojunho/unittwelve/SamsungTV.java
src/main/java/org/example/advaned/gojunho/unittwelve/TV.java
src/main/java/org/example/basic/gojunho/unitfourteen/AnnotatedClass.java
src/main/java/org/example/basic/gojunho/unitfourteen/AnnotationReader.java
src/main/java/org/example/basic/gojunho/unitfourteen/BasicAnnotationExample.java
src/main/java/org/example/basic/gojunho/unitfourteen/TestInfo.java

basic Annotation
advaned BridgePattern

basic unitfourteen, advaned unittwelve complete

---

src/main/java/org/example/basic/parkminji/unitfourteen/AnnotatedClass.java
src/main/java/org/example/basic/parkminji/unitfourteen/AnnotationReader.java
src/main/java/org/example/basic/parkminji/unitfourteen/BasicAnnotationExample.java
src/main/java/org/example/basic/parkminji/unitfourteen/TestInfo.java

Java 어노테이션 실습 과제
기본 내장 어노테이션 사용 예제와 커스텀 어노테이션 정의 및 리플렉션 활용 예제를 포함
---
- `@Deprecated`, `@Override` 기본 어노테이션 사용 예제
- 사용 중단된 메서드와 오버라이딩 메서드 출력
- 커스텀 어노테이션 `@TestInfo` 정의
- `@Retention(RUNTIME)`, `@Target(METHOD)` 설정
- `@TestInfo` 어노테이션을 메서드에 적용
- 작성자와 작성일 정보 부여
- 리플렉션으로 어노테이션 정보를 런타임에 추출
- `Method.getAnnotation()`과 `isAnnotationPresent()` 활용
---

feat: 어노테이션 실습 과제 (unitfourteen) 코드 추가

---

src/main/java/org/example/basic/bangjihyun/unitfifteen/ListExample.java
src/main/java/org/example/basic/bangjihyun/unitfifteen/MapExample.java
src/main/java/org/example/basic/bangjihyun/unitfifteen/QueueExample.java
src/main/java/org/example/basic/bangjihyun/unitfifteen/SetExample.java
src/main/java/org/example/basic/bangjihyun/unitfourteen/AnnotatedClass.java
src/main/java/org/example/basic/bangjihyun/unitfourteen/AnnotationReader.java
src/main/java/org/example/basic/bangjihyun/unitfourteen/BasicAnnotationExample.java
src/main/java/org/example/basic/bangjihyun/unitfourteen/TestInfo.java

🍎 Java 컬렉션 정리: List, Set, Map, Queue 개념 및 예제 추가.

(feat) unit fourteen and fifteen complete

---

src/main/java/org/example/advaned/kimaram/unitthirteen/Directory.java
src/main/java/org/example/advaned/kimaram/unitthirteen/File.java
src/main/java/org/example/advaned/kimaram/unitthirteen/FileComponent.java
src/main/java/org/example/advaned/kimaram/unitthirteen/Main.java
src/main/java/org/example/basic/kimaram/unitfifteen/ListExample.java
src/main/java/org/example/basic/kimaram/unitfifteen/MapExample.java
src/main/java/org/example/basic/kimaram/unitfifteen/QueueExample.java
src/main/java/org/example/basic/kimaram/unitfifteen/SetExample.java

- Collection (List, Set, Map, Queue)
- Composite 패턴 
📂 src/main/java/org/example/basic/kimaram/unitfifteen/
```
├── ListExample.java
├── MapExample.java
├── QueueExample.java
└── SetExample.java
```
📂 src/main/java/org/example/advaned/kimaram/unitthirteen/
```
├── Directory.java
├── File.java
├── FileComponent.java
└── Main.java
```

Kimaram 0731 과제 PR 요청

---

src/main/java/org/example/basic/gojunho/unitsixteen/ecr_workflows.yaml

github action을 통해 이미지를 빌드 후 ecr에 배포하고 서비스를 재기동

(feat) basic unitsixteen complete

---

src/main/java/org/example/basic/yunbyeongchang/unitsixteen/Deploy.yml

배포용 yml 파일 작성 완료
+ main branch에 push 시 자동 action
+ workflow_dispatch를 사용하여 수동 action 가능
++ 수동 action의 경우 deploy와 restart 2가지 기능 중 선택 가능
+ Checkout source
+ Configure AWS credentials
+ Login to Amazon ECR
+ Build and push Docker image to ECR(restart일 경우 시행하지 않음)
+ Deploy or Restart ECS Service

feat: basic unitsixteen completed

---

src/main/java/org/example/basic/taebinlee/unitfifteen/ListExample.java
src/main/java/org/example/basic/taebinlee/unitfifteen/MapExample.java
src/main/java/org/example/basic/taebinlee/unitfifteen/QueueExample.java
src/main/java/org/example/basic/taebinlee/unitfifteen/SetExample.java
src/main/java/org/example/basic/taebinlee/unitfourteen/AnnotatedClass.java
src/main/java/org/example/basic/taebinlee/unitfourteen/AnnotationReader.java
src/main/java/org/example/basic/taebinlee/unitfourteen/BasicAnnotationExample.java
src/main/java/org/example/basic/taebinlee/unitfourteen/TestInfo.java
src/main/java/org/example/basic/taebinlee/unitsixteen/deploy.yml

unit sixteen 과제 순서
1. 본인의 레파지토리를 github action 으로 자동 배포
2. 사전에 만들어 놓은 개인 ECS 에 배포되도록 함.
3. github action 성공한 스크립트를 yml 파일로 basic 숙제 폴더에 업로드 한다.
4. main 브랜치에 배포가 되면 자동으로 배포된다.
5. ecs service 재기동 되도록 하여 서버에 변경된게 잘 배포 되는지 확인.

 unitfourteen, fifteen, sixteen 과제 제출

---

src/main/java/org/example/basic/parkminji/unitseventeen/Calculator.java
src/main/java/org/example/basic/parkminji/unitseventeen/CalculatorMain.java
src/main/java/org/example/basic/parkminji/unitseventeen/Operation.java
src/main/java/org/example/basic/parkminji/unitseventeen/OperationRegistry.java
src/main/java/org/example/basic/parkminji/unitseventeen/OperatorType.java
src/main/java/org/example/basic/parkminji/unitseventeen/operations/AddOperation.java
src/main/java/org/example/basic/parkminji/unitseventeen/operations/DivideOperation.java
src/main/java/org/example/basic/parkminji/unitseventeen/operations/MultiplyOperation.java
src/main/java/org/example/basic/parkminji/unitseventeen/operations/SubtractOperation.java
src/main/java/org/example/basic/parkminji/unitsixteen/deploy-to-ecs.yml
src/main/java/org/example/basic/parkminji/unitsixteen/task-definition.json

Java 리팩토링, 전략(Strategy) 패턴을 활용한 Calculator 구현
---
- `Operation` 인터페이스 정의
- `OperatorType` enum으로 매직 스트링 제거 및 타입 안정성 확보
- `AddOperation`, `SubtractOperation`, `MultiplyOperation`, `DivideOperation` 클래스 각각 구현
- Divide는 0으로 나눌 경우 예외 처리 포함
- 연산자 타입과 연산 전략 객체를 매핑하는 전용 레지스트리 클래스
- 연산 추가 시 코드 변경 최소화
- `calculate(String operator, int a, int b)` 메서드에서 enum 변환 후 전략 객체 실행
- 지원하지 않는 연산자, 0으로 나누기 등 예외 처리 포함
- `main()`은 별도 클래스로 작성
- `runTest()` 메서드로 각 연산자별 테스트 케이스 구성
- 출력 로직과 예외 메시지는 각각 메서드로 분리하여 가독성 향상
---
```text
add(5, 3) = 8 (예상: 8) [PASS]
sub(10, 4) = 6 (예상: 6) [PASS]
mul(3, 7) = 21 (예상: 21) [PASS]
div(20, 5) = 4 (예상: 4) [PASS]
div(10, 0) 예외 발생 예상대로: 0으로 나눌 수 없습니다. [PASS]
mod(10, 3) 예외 발생 예상대로: 잘못된 연산자입니다: mod [PASS]
```

리팩토링, Strategy 기반 Calculator 구현 및 실행 클래스 분리 (Unit 17)

---

src/main/java/org/example/basic/leeseungyeon/unitseventeen/AddOperation.java
src/main/java/org/example/basic/leeseungyeon/unitseventeen/Calculator.java
src/main/java/org/example/basic/leeseungyeon/unitseventeen/DivOperation.java
src/main/java/org/example/basic/leeseungyeon/unitseventeen/MulOperation.java
src/main/java/org/example/basic/leeseungyeon/unitseventeen/Operation.java
src/main/java/org/example/basic/leeseungyeon/unitseventeen/OperationFactory.java
src/main/java/org/example/basic/leeseungyeon/unitseventeen/SubOperation.java

전략(Strategy) 패턴을 활용한 Java Calculator Refactoring
---
- 모든 연산의 공통 규약 정의
- `apply(int a, int b)` 메서드 통일
- `AddOperation`, `SubOperation`, `MulOperation`, `DivOperation`
- 각 연산별 독립 클래스로 단일 책임 원칙 준수
- 연산 객체 생성 및 관리
- 런타임 연산 추가/제거 지원
- `calculate(String operator, int a, int b)` 메인 메서드
- 다양한 생성자로 유연한 초기화
---
- **if-else 지옥 제거** → 깔끔한 코드 구조
- **확장성 향상** → 새 연산 쉽게 추가
- **테스트 용이성** → 각 연산 독립 테스트 가능

feat: unitseventeen

---

src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/example/DiscountStrategy.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/example/FixedDiscount.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/example/Main.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/example/Order.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/example/RateDiscount.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/homework/Base64Encoding.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/homework/EUCKREncoding.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/homework/EncoderContext.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/homework/EncodingStrategy.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/homework/HexEncoding.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/homework/Main.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/homework/UTF8Encoding.java
src/main/java/org/example/advaned/yunbyeongchang/unitfourteen/struct.txt
src/main/java/org/example/basic/yunbyeongchang/unitseventeen/Add.java
src/main/java/org/example/basic/yunbyeongchang/unitseventeen/Calculator.java
src/main/java/org/example/basic/yunbyeongchang/unitseventeen/Divide.java
src/main/java/org/example/basic/yunbyeongchang/unitseventeen/DivideByZeroException.java
src/main/java/org/example/basic/yunbyeongchang/unitseventeen/Main.java
src/main/java/org/example/basic/yunbyeongchang/unitseventeen/Multiply.java
src/main/java/org/example/basic/yunbyeongchang/unitseventeen/Operation.java
src/main/java/org/example/basic/yunbyeongchang/unitseventeen/Substraction.java

basic
+ Calculator Class 리팩토링
+ Interface 생성 후 기능 분리
+ Strategy Pattern 사용하여 유지보수에 용이하도록 설계
advanced
+ Strategy Pattern 예제 공부
+ Base64, Hex, UTF-8, EUC-KR 방식으로 인코딩/출력

feat: basic unitseventeen / advanced unitfourteen completed

---

src/main/java/org/example/basic/bangjihyun/unitseventeen/AddOperation.java
src/main/java/org/example/basic/bangjihyun/unitseventeen/Calculator.java
src/main/java/org/example/basic/bangjihyun/unitseventeen/DivOperation.java
src/main/java/org/example/basic/bangjihyun/unitseventeen/Main.java
src/main/java/org/example/basic/bangjihyun/unitseventeen/MulOperation.java
src/main/java/org/example/basic/bangjihyun/unitseventeen/Operation.java
src/main/java/org/example/basic/bangjihyun/unitseventeen/OperationFactory.java
src/main/java/org/example/basic/bangjihyun/unitseventeen/SubOperation.java

🍎활동
if-else 조건문을 Strategy 패턴으로 리팩토링했음
Operation 인터페이스와 Factory를 도입해 OCP 적용했음
Calculator는 연산만 수행하도록 SRP 적용했음
Main에서 사용자 입력으로 동작 테스트 가능함
🍎어려웠던 점:
Factory로 연산 클래스 매핑하는 구조 설계가 어려웠음
인터페이스-구현체 연결을 단순하게 유지하는 게 고민이었음

(feat) unit seventeen complete

---

src/main/java/org/example/basic/leeseungyeon/uniteighteen/CoffeeOrder.java
src/main/java/org/example/basic/leeseungyeon/uniteighteen/CoffeeOrderManager.java
src/main/java/org/example/basic/leeseungyeon/uniteighteen/CoffeeSize.java
src/main/java/org/example/basic/leeseungyeon/uniteighteen/CoffeeType.java
src/main/java/org/example/basic/leeseungyeon/uniteighteen/Main.java

Enum을 활용한 커피 주문 시스템 만들기
---
🎯 **주제**  
Java enum으로 커피 종류와 사이즈 관리, 주문 시스템 구현
---
**구현 내용**
- CoffeeType, CoffeeSize enum에 이름, 가격, 용량 정보 포함  
- CoffeeOrder record로 주문 데이터 모델링 및 가격 계산  
- OrderValidator로 입력값 검증  
- CoffeeOrderManager에서 주문 처리 및 출력  
- Main에서 프로그램 실행
---
**개선 효과**
- 타입 안전성과 코드 간결성 증가  
- 입력 검증 분리로 유지보수 용이  
- enum 수정만으로 기능 확장 가능  
- 안정적인 사용자 인터페이스 제공

feat: uniteighteen - CoffeeOrder record

---

src/main/java/org/example/basic/bangjihyun/uniteightteen/CoffeeOrder.java
src/main/java/org/example/basic/bangjihyun/uniteightteen/CoffeeSize.java
src/main/java/org/example/basic/bangjihyun/uniteightteen/CoffeeType.java
src/main/java/org/example/basic/bangjihyun/uniteightteen/Main.java

🍎커피 주문 시스템 구현:
- CoffeeType enum에 커피 종류 및 가격 추가했음.
- CoffeeSize enum에 사이즈별 용량 추가했음.
- CoffeeOrder 클래스에서 주문 내역 출력 기능 구현했음.
- Main 클래스에서 사용자 입력 받아 주문 처리하도록 했음.
- 잘못된 입력 시 예외 처리하도록 했음.
- 반복 주문 기능 추가했음.
🍎어려웠던 점:
- enum에 가격 정보를 넣고 관리하는 방식
- 사용자 입력을 받을 때 잘못된 값이 들어왔을 때 예외 처리
- 반복 주문 기능을 구현하며 반복문과 예외 처리를 적절히 조합하는 데 시간이 걸렸음.

(feat) unit eightteen complete
